### ISSUE TITLE
CharRegions

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#107]
I'm attempting to extract matched characters by using pipeline->charRegions but it also contains unmatched characters (not pruned by regex filter). How would i go about skipped these?

**Comment by matthill** [comment]
The regex filter is only applied to complete plate results, rather than individual characters.  For example, it's possible that AB123 doesn't match, but ABC123 does match.  Similarly, it's possible that ABCL23 doesn't match, but ABC123 does.  

The only way to do what (I think) you want to do, is to parse the top n results.

**Comment by peters** [comment]
I'll try that and get back to you :+1:
