### ISSUE TITLE
Support for Australian number plates.

### ISSUE THREAD

**Issue by shadow7412** [openalpr/openalpr#119]
I'm not sure how easy this would be, but it would be awesome if support for Australian number plates was added to this software.

Part of the reason why I'm not sure how easy this would be comes down to number plates generally varying from state to state. http://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Australia has a pretty good analysis of the differences.

**Comment by matthill** [comment]
I'll be working on exactly this project over the next few weeks.  The result will be a new detector and OCR set for Australia.  If you have any plate images to contribute, now is a great time to upload them so I can make use of them.  I have a bank of images from another user, but I definitely could use more.

**Comment by shadow7412** [comment]
Awesome to hear :D I'll see what I can dig up for you.

**Comment by jasonhurd** [comment]
Are there any specific requirements for submitting plate images? Such as, cropped, straight on, clear etc? I have been collecting images from our weighbridge for a while in hopes to try and train for aussie plates. Quite a few are the same plate number though. Would it be helpful to have duplicate numbers taken at different times?

**Comment by matthill** [comment]
It should be clearly legible to a human.  The rotation and angles shouldn't be too severe, but a little bit is fine.  Duplicate numbers are also fine as long as there's variation (i.e., not 70% are all the same plate number).

**Comment by matthill** [comment]
Anything you can upload at this point will be useful.  I'm going to start training the images very soon.  The more images we get, the better the accuracy will be.  If you have anything,  you can upload (FTP) to upload.openalpr.com

**Comment by Bigben83** [comment]
I have been waiting for Australian Plates,  I will be able to provide unlimited pictures off a few of my cameras.  Will be watching this carefully.

**Comment by Bigben83** [comment]
I should have mentioned these will be Tasmanian Plates.

**Comment by matthill** [comment]
Excellent.  Please upload the Tasmanian plates if you can.  If you can upload them within the next week or so, I can make use of them.

**Comment by Bigben83** [comment]
Ok I have added a small batch of Tas plates, but I will change the lens on my camera tomorrow and let it run again, so we have bigger plates. and will upload another batch tomorrow night.

**Comment by matthill** [comment]
Awesome, I'll pull them down and add them to the detector.  I should be done later this week.  The last thing I need is a handful (50 or so) of frontal shots of Victoria plates to finish the OCR training.  I couldn't find a sufficient number off of the internet.

**Comment by matthill** [comment]
https://github.com/openalpr/openalpr/commit/e55c4a7070af06568a82de7c67b189ecc920ad50

**Comment by sboyd1973** [comment]
Hey Matt,
It is greatly appreciated that you have gone to the trouble of now creating an Australian library. I am wondering whether this works for all Australian plates or only certain regions? The state of Victoria has 43 different plate types alone!   ( https://www.vplates.com.au/index.php?page=create-plate )
Are further plates needed or does the current OCR handle all types already>
Thanks.

**Comment by Karem-Elzftawy** [comment]
Hello @matthill 
Did you finish the train and OCR for the Australian License plates?

**Comment by owl770** [comment]
Hi @matthill
Just wanted to know if the Australian training data included plates from New South Wales (NSW)?
Thanks.

**Comment by gbrits** [comment]
Does anyone have an updated Australian set of trained data? As it stands, my Australian app is currently getting about a 50% accuracy rate with the traineddata @matthill has been so kind to provide - I would love to be able to enhance / add license plates to the training and make it more accurate if I can be steered in the right direction?

**Comment by owl770** [comment]
Hi @gbrits - i have pretty good success with country set to 'auwide' (rather than 'au'). Have you tried that?

**Comment by gbrits** [comment]
Ended up switching to a paid API instead, far more trained & accurate @owl770, sorry, not sure if that was the solution or not

**Comment by PhantomRay** [comment]
> Ended up switching to a paid API instead, far more trained & accurate @owl770, sorry, not sure if that was the solution or not

Mind asking what the paid API is?

**Comment by kingstar788** [comment]
i need Support for Iraq number plates?

**Comment by dawood750** [comment]
DOES anyone have an updated Australian set of trained data?

**Comment by owl770** [comment]
> DOES anyone have an updated Australian set of trained data?

I get quite good results from these config settings:

`country = auwide`
`pattern = nsw`

**Comment by dawood750** [comment]
; Specify the path to the runtime data directory
runtime_dir = runtime_data


ocr_img_size_percent = 1.33333333
state_id_img_size_percent = 3.0

; Calibrating your camera improves detection accuracy in cases where vehicle plates are captured at a steep angle
; Use the openalpr-utils-calibrate utility to calibrate your fixed camera to adjust for an angle
; Once done, update the prewarp config with the values obtained from the tool
prewarp = 

; detection will ignore plates that are too large.  This is a good efficiency technique to use if the 
; plates are going to be a fixed distance away from the camera (e.g., you will never see plates that fill 
; up the entire image
max_plate_width_percent = 80
max_plate_height_percent = 80

; detection_iteration_increase is the percentage that the LBP frame increases each iteration.
; It must be greater than 1.0.  A value of 1.01 means increase by 1%, 1.10 increases it by 10% each time. 
; So a 1% increase would be ~10x slower than 10% to process, but it has a higher chance of landing 
; directly on the plate and getting a strong detection
detection_iteration_increase = 1.01

; The minimum detection strength determines how sure the detection algorithm must be before signaling that 
; a plate region exists.  Technically this corresponds to LBP nearest neighbors (e.g., how many detections 
; are clustered around the same area).  For example, 2 = very lenient, 9 = very strict.
detection_strictness = 2

; The detection doesn't necessarily need an extremely high resolution image in order to detect plates
; Using a smaller input image should still find the plates and will do it faster
; Tweaking the max_detection_input values will resize the input image if it is larger than these sizes 
; max_detection_input_width/height are specified in pixels
max_detection_input_width = 1400
max_detection_input_height = 1216

; detector is the technique used to find license plate regions in an image.  Value can be set to
; lbpcpu    - default LBP-based detector uses the system CPU  
; lbpgpu    - LBP-based detector that uses Nvidia GPU to increase recognition speed.
; lbpopencl - LBP-based detector that uses OpenCL GPU to increase recognition speed.  Requires OpenCV 3.0
; morphcpu  - Experimental detector that detects white rectangles in an image.  Does not require training.
detector = lbpcpu

; If set to true, all results must match a postprocess text pattern if a pattern is available.  
; If not, the result is disqualified. 
must_match_pattern = 0

; Bypasses plate detection.  If this is set to 1, the library assumes that each region provided is a likely plate area.
skip_detection = 0

; Specifies the full path to an image file that constrains the detection area.  Only the plate regions allowed through the mask 
; will be analyzed.  The mask image must match the resolution of your image to be analyzed.  The mask is black and white.  
; Black areas will be ignored, white areas will be searched.  An empty value means no mask (scan the entire image)
detection_mask_image = 

; OpenALPR can scan the same image multiple times with different randomization.  Setting this to a value larger than
; 1 may increase accuracy, but will increase processing time linearly (e.g., analysis_count = 3 is 3x slower)
analysis_count = 2

; OpenALPR detects high-contrast plate crops and uses an alternative edge detection technique.  Setting this to 0.0 
; would classify  ALL images as high-contrast, setting it to 1.0 would classify no images as high-contrast. 
contrast_detection_threshold = 0

max_plate_angle_degrees = 15

ocr_min_font_point = 6

; Minimum OCR confidence percent to consider.
postprocess_min_confidence = 65

; Any OCR character lower than this will also add an equally likely
; chance that the character is incorrect and will be skipped.  Value is a confidence percent
postprocess_confidence_skip_level = 80


debug_general         = 0
debug_timing          = 0
debug_detector        = 0
debug_prewarp         = 0
debug_state_id        = 0
debug_plate_lines     = 0
debug_plate_corners   = 0
debug_char_segment    = 0
debug_char_analysis   = 0
debug_color_filter    = 0
debug_ocr             = 0
debug_postprocess     = 0
debug_show_images     = 0
debug_pause_on_frame  = 0



this is my conf

**Comment by dawood750** [comment]
;The few lines starting with "char_analysis_min_pct" try to find the characters on the plate.It starts at 35% of the plate height (in this case) and searches for similar sized letters between 35-50% of the plate height, then 45-60%, then 55-70%... and stops looking at 75-90%

; 35-50; 45-60, 55-70, 65-80, 75-90

char_analysis_min_pct = 0.35
char_analysis_height_range = 0.15
char_analysis_height_step_size = 0.5
char_analysis_height_num_steps = 5

segmentation_min_speckle_height_percent = 0.3
segmentation_min_box_width_px = 4
segmentation_min_charheight_percent = 0.4;
segmentation_max_segment_width_percent_vs_average = 1.6;

;The plate_width/height mm is millimeters of the ideal plate when looking straight on. Just use standard australian lisence plate measurements.

plate_width_mm = 372       
plate_height_mm = 135

multiline = 0

; the whitespace top and whitespace bottom are measurements for how much gap there is between the characters and the top of the plate. 

char_height_mm = 82
char_width_mm = 45
char_whitespace_top_mm = 18  
char_whitespace_bot_mm = 30

;template_max_width/height should be a multiple of the aspect ratio that your detector was trained against.  A smaller value here makes processing faster,but could degrade accuracy

template_max_width_px = 184  
template_max_height_px = 100

; Higher sensitivity means less lines
plateline_sensitivity_vertical = 22
plateline_sensitivity_horizontal = 50

; Regions smaller than this will be disqualified
min_plate_size_width_px = 85
min_plate_size_height_px = 28

; Results with fewer or more characters will be discarded
postprocess_min_characters = 4
postprocess_max_characters = 8

ocr_language = lau

; Override for postprocess letters/numbers regex. 
postprocess_regex_letters = [A-Z]
postprocess_regex_numbers = [0-9]


; Whether the plate is always dark letters on light background, light letters on dark background, or both
; value can be either always, never, or auto
invert = auto
for au this

**Comment by dawood750** [comment]
any recommendations what should be improved for accuracy

**Comment by dawood750** [comment]
any recommendations what should be improved for accuracy?
