### ISSUE TITLE
Loading regex patterns during startup is super slow

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#173]
Takes about 10 seconds.

![image](https://cloud.githubusercontent.com/assets/869/9134035/dd38ca32-3d00-11e5-8b58-75d7270f7954.png)

**Comment by matthill** [comment]
Thanks for noticing that.  I had noticed that startup was much slower, but hadn't figured out what was causing it.  It looks like RE2 takes much longer to load when parsing Unicode values.

I entered this issue: https://github.com/google/re2/issues/46

I'll wait to hear back -- hopefully it's something that can be tweaked in the library to make it faster.

If not, I'll add a configurable option to each country where you can specify ASCII or Unicode.

You can see the difference if you change RegexRule as follows:
      else if (utf_character == "@")
      {
        regexval << "[A-Z]";
      }
      else if (utf_character == "#")
      {
        regexval << "[0-9]";
      }

Startup time goes from ~1.7 seconds to 50ms.

**Comment by matthill** [comment]
The re2 folks replied and mentioned that re2 is necessarily going to be slower, since it compiles in all the thousands of possible characters.  

Another option is to query Tesseract to find out exactly which characters are included in the training set.  Then use a single general regex to pick out all the letters/digits.  Then just use that smaller subset of unicode letters/digits to build all the regexes.  That should be a lot faster, and work generically with any language without needing special configuration.

**Comment by peters** [comment]
> The re2 folks replied and mentioned that re2 is necessarily going to be slower, since it compiles in all the thousands of possible characters.

Aha.

> Another option is to query Tesseract to find out exactly which characters are included in the training set. Then use a single general regex to pick out all the letters/digits. 

I agree :+1:

**Comment by matthill** [comment]
Should now be resolved after these commits:
6e94703dea53a0b48312a22c57bbcc602ba72a1c
28aed1b7d978d4143c0e942fe1b829f846d98f28

I scoured the Tesseract API, but there was no way of doing what I suggested earlier without code changes.  I added a config option for each country where the regex pattern for digits vs numbers can be specified.  Load time is *much* faster now.
