### ISSUE TITLE
Not recognizing eu number plates

### ISSUE THREAD

**Issue by onno182** [openalpr/openalpr#177]
EU number plates do not get recognized, while US do.

![lp](https://cloud.githubusercontent.com/assets/13760619/9217791/359695aa-40cc-11e5-9131-7b9a1a5a3a55.jpg)

When using using attached image:

alpr -c eu lp.jpg
No license plates found.

 alpr -c us lp.jpg
plate0: 1 results
    - L87E       confidence: 83.688
plate1: 7 results
    - 87RSR      confidence: 88.2947
    - 87R5R      confidence: 79.1333
    - 87RR       confidence: 76.2563
    - 87RBR      confidence: 73.8303
    - 87RS       confidence: 72.3227
    - 87R5       confidence: 63.1613
    - 87RB       confidence: 57.8583

**Comment by onno182** [comment]
Anyone have any ideas?

**Comment by onno182** [comment]
Incase someone has the same problem, setting the following seemed to have fixed the problem.

detection_iteration_increase = 1.1

to

detection_iteration_increase = 1.5

**Comment by matthill** [comment]
I ran OpenALPR on the image.  If you run 100 images through that look similar to this, you'll probably get 98 correct results.  There's just a small chance that it doesn't pick up the features.  It's just the nature of computer vision -- it will never be 100%.  There's some discussion about this in the forum: https://groups.google.com/forum/#!searchin/openalpr/computer$20vision/openalpr/vpky-7qFXSI/F_Fcjy9cqt4J

Changing the detection_iteration_increase value results in essentially a different chance at reading the plate (since the area being analyzed will be ever-so-slightly different).  If you changed it to 1.09 or 1.11, I suspect that will make it read correctly as well.

**Comment by BramWerbrouck** [comment]
I have a similor probleem, it’s like the API cloud Version Works corrector than the ‘general’ version.
when I Change “us” into “eu” (because I want to read licence plates from Europe) I get An Error.

I used this in my python script:
Plate = ALPR(“eu” , “/etc/openalpr/openalpr.conf” , “/usr/share/openalpr/runtime_data”)

The EU Sems logical to me, but it doens’t work.. what do I do wrong?

**Comment by Wikinaut** [comment]
Same problem here.
