### ISSUE TITLE
Incorrect detection position

### ISSUE THREAD

**Issue by renatoneto** [openalpr/openalpr#197]
I'm using for test the brazilian plate "FMW 3777",
but in the possibilities it's showing me "FMH 3777" as correct, and "FMW 3777"
as second position. 

How can I do to show "FMW 3777" as first position?

I've trained the program for brazilian plates.

My unicharambigs:
v2
H W 0

http://i.imgur.com/qigfK0N.png

Others plates tests:
http://i.imgur.com/CMgcuqQ.png
http://i.imgur.com/LXVLl7E.png

thanks!

**Comment by Silex** [comment]
I think you need to train it with more plates.

**Comment by vladimirr0708982** [comment]
for start you need to train more detector after OCR
minimum 3000 image for detector...

**Comment by matthill** [comment]
Yes, I think you need to train your OCR with more "W" and "H" characters.  I wouldn't mess with unicharambigs, since that tells the OCR to always provide both (i.e., whenever it sees a W, send an H as well and vice versa).  The characters do look similar when binarized, but they are different enough to be differentiated with sufficient OCR training.
