### ISSUE TITLE
Add GPU support via OpenCL for faster recognition

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#2]
OpenCL support can be added for license plate detection, binarization, and (in the next version of Tesseract) OCR.  This would significantly improve the recognition speed..

**Comment by marabej** [comment]
Hi,
Can you tell, what model video card you used, which version of cuda drivers 5.5 / 6.0 / 6.5 / 7.0, what OS when you tested with gpu?

**Comment by Kees-V** [comment]
Hi Marabej,
I have an AMD Radeon(TM) HD8970M and I am using it on Windows 8.1 Professional 64bit with AMD Catalyst 14.12.
This week I have updated the library to OpenCV 3.0 RC1.
By the way: The OpenALPR-fork I mentioned in the December post has been deleted.
If you are interested I could try to upload a ZIP-file with executable + required dlls as a release to illustrate OCL operation.

**Comment by marabej** [comment]
Hi, I not problem please upload exe+dll, but actually I'm interested under linux. I'm trying with ubuntu 14.04. openalpr is working like a charm except cuda support. My video card is an older geforce 8600 gt, but I readed, thet it has compute capability 1.1 on theory it should work. Cuda I used 5.5. One error which I found was with cvtColor function, I think wrong number color channel in input image and I took the condition from the cpu detector. But after that I saw another error and I think the problem is in the video card / driver / cuda. Yesterday I made a fresh install of my Ubuntu on another hard disk and cuda 5.5, but I didn't test it yet. Tell me your email please If there is no problem,. My email is: marabej@gmail.com

**Comment by Kees-V** [comment]
Hi Marabej,
Please note that OpenCL is different from CUDA.
I am afraid I cannot advise you on the use of CUDA on Linux, other than that use of compute capability 1.1 may require a special setting in the make-phase of OpenCV, see http://docs.opencv.org/2.4.9/modules/gpu/doc/introduction.html

**Comment by marabej** [comment]
Hi Kees-V.
10x for the link. I read it and I think that for 1:1 cappabilities there is no need for changing the setting. When I tried it the last time, openCV compilled flawlessly. After that I received errors when tried alpr. I will try again on the fresh ubuntu 14.04. I will try also in windows 8.1 if you upload exe+dlls :)

**Comment by marabej** [comment]
Hi
I succeeded in cimpiling OpenCV 3.0RC1 under ubuntu 14.04. Obviously it has accelerated LBP cascades but  I don't know why they don't work properly (or I'm wrong with something). I checked for instance their samples. The program cascadeclassifier.php I tried with cascade:  lbpcascade_frontalface.xml and input image lp.jpg for alpr example worked (of coarse that cascade file is not for plates, but I want just to see work or not OpenCV with accelerate LBP cascades). Than I tried with another cascade file from OpenCV examples:  lbpcascade_profileface.xml and It worked. I tried after that with cascade us.xml from alpr and It exits with error. Obviously OpenCV worked with One cascades, but doesn't work with another. 
The problem is that the function detectMultiScale works with some LBP xml files but no with another. It returned huge number of detected elements and after that for example in detectorcuda.cpp the row: plateregions_buffer.colRange(0, numdetected).download(plateregions_downloaded); returns error.
I don't know where is the problem: my old nvidia 8600GT card or in OpenCV. Alpr doesn't want to compile with OpenCV 3.0 (there are a lot of errors "error: cannot allocate an object of abstract type ‘cv::FastFeatureDetector’" in featurematcher.cpp. Obviously OpenCV 3.0 developers made their FastFeatureDetector class as abstract and  that must be fixed on alpr side. I tried sample HAAR cascades in OpenCV 3.0 and OpenCV 2.4.9 and they worked (didn't exits with error. In OpenCV 2.4.9 LBP XML didn't work, but in OpenCV 3.0 some of them worked).

**Comment by Kees-V** [comment]
Hi Marabej,
If you can live without the featurematcher (which is optionally used for state-detection in US-plates) for your test, then you can workaround the complie errors by commenting out  the BFMatcher, FastFeatureDetector and BRISK lines in FeatureMatcher::FeatureMatcher(Config* config). 
You will also need to apply the change to platelines.cpp described above.
After that the compile of ALPR with OpenCV 3.0 should be possible.

**Comment by robertocarvajal** [comment]
Thanks, I tested this and worked, it is a lot faster actually! I made a branch here if any of you want to give it a try: https://github.com/robertocarvajal/openalpr/tree/opencv3 the patch is really simple, just a conditional if macro for testing CV_MAJOR_VERSION and had to replace the adaptativeBilateralFilter because it was dropped out opencv3 for low quality, the exact patch is just 3 lines, here:

https://github.com/robertocarvajal/openalpr/commit/574923972e18d290ddca2a7fb1f0dc104e033c3b

now, of course this drops support for the state recognition so this is not meant as a complete patch, just to try out opencv3 which I think openalpr should try to support soon, the improvement is great and there is really not much to change at all.

**Comment by marabej** [comment]
Hi

I also suceeded with GPU. I te4sted now with ATI R7 240 card and is faster. I found a serious bug in all branches of openalpr which I tested. Periodically threads are crashing  with error:
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /opencv-3.0.0-rc1/modules/core/src/matrix.cpp, line 496 terminate called after throwing an instance of 'cv::Exception'

The problem is in alpr_impl.cpp. Sometimes it calls LicensePlateCandidate with invalid region and the process crashes. OpencCv has a cherc for valid regions. 
Here is a small example with my debug lines:
expandedRegion.x=214 
expandedRegion.y=642 
expandedRegion.width=318 
expandedRegion.height=80
this->pipeline_data->grayImg.cols 1280
this->pipeline_data->grayImg.rows 720
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /marabej/opencv/Ubuntu/OpenCV/opencv-3.0.0-rc1/modules/core/src/matrix.cpp, line 496
terminate called after throwing an instance of 'cv::Exception'
642+80 = 722    =>    722 > 720  => crash :)
Such type of error I found and in the newest git version here (but maybe in another part of code, I will checked it, but in the test after 40-50 min.l of work It crashed with the same error.

My fix:  
in alpr_impl.cpp

for (unsigned int i = 0; i < response.plateRegions.size(); i++)
plateQueue.push(response.plateRegions[i]);

**Comment by Kees-V** [comment]
I saw similar issues using OpenCV 3.0 RC and proposed a simillar fix in OpenALPR, see:
https://github.com/Kees-V/openalpr/commit/210d41fdf4b2639af063802b4fb6cf796d2604ea
But it is a liitle early to do this, the issue may be solved in the final release of OpenCV 3.0.

**Comment by marabej** [comment]
Hi Kees-V

Thank you

I think that we are wrong both. Because I saw that 3-4 times it worked, but the next moment it crashed. 
I think that is the problem:
 if (!plateDetected)
      {
        // Not a valid plate
        // Check if this plate has any children, if so, send them back up for processing
        for (unsigned int childidx = 0; childidx < plateRegion.children.size(); childidx++)
        {
          plateQueue.push(plateRegion.children[childidx]);
        }
      }
The program saw valid region and began the  "while". but if there is children, they were "pushed" in the queue. After that one of them had a wrong region and the system crashed. We mad our logical check before the cycle "while", and now I put it inside. I put also "break;" It's better to break the "while", than started to work with "the children". I tried without "break" but the system crashed with a message "corrupted double-linked list". Now I am waiting :)
Excuse me for my bad English :)


I am testing from an hour with a little different fix. I put my code in while(  statement

**Comment by marabej** [comment]
It crashed again with:

Region Problem: roi.x: 244 roi.y: 677 roi.width: 180 roi.height: 45 img.cols: 1280 img.rows: 720
Region must match the condition: (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= img.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= img.rows) 
Error: signal 11:
alprd(_Z16segfault_handleri+0x1c)[0x4305d9]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f9e25036d40]
[0x7f9e00000268]

The first rows are my messages. 2 hours uptime :)

**Comment by robertocarvajal** [comment]
I actually have a border check for the same reason, basically before setting a region I check if there is enough space for that region inside the image if not I just bound to border.. I have a feeling that something changed recently though, I get less accurate detection after the last update I ran, still haven't figured it out completely yet..

**Comment by marabej** [comment]
Hi
I solved the problem "rough". Make the chek before the "for" which pushes plates into plateQueue. This cjheck can I can put inside this for and then return response, nut decided for test to put in new cycle for before the definition of the variable plateQue. I made different for just for checking the regions and put "return response". It's bad solution but works nicely. In this way I lost one frame, but it's better to lose one frame than hangs the whole process. I checked 8 hours without a problem. The processes tried to hangs many times, maybe 10-15, but worked. I saw the messages with invalid regions, but worked

**Comment by matthill** [comment]
It sounds like perhaps the new version of OpenCV is returning regions from the Cascade detector that are outside the bounds of the image?

I just made a change that may help.  I haven't reproduced the problem though, so I may be completely wrong.
https://github.com/openalpr/openalpr/commit/a8499e3d0d81bc7631deb8d7b0a119485b61f324

**Comment by marabej** [comment]
Hi Matthill and 10x
That fixed the problem 100% I think. I tested for approximately 12 hours without any problem.If I notice another problem I'll write

**Comment by matthill** [comment]
Added a new OpenCL detector that works with OpenCV 3.0 (lbpopencl) -- ec24d1d1474e2acecd3dcf48df37d980e125141d

I benchmarked it on my Intel NUC NUC5i5RYK -- it's fast.  Using the latest Beignet OpenCL drivers, it fully loads the GPU with the detection processing.  I was seeing ~50ms per detection at 1280x720.  Almost real-time performance on $400 hardware.

**Comment by anhlt309** [comment]
When I run my app, output: OpenCL not detected. What's wrong? I'm using opencv 3.1

**Comment by Kees-V** [comment]
That's strange...
-Which GPU and CPU are in your computer?

**Comment by anhlt309** [comment]
My CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
GPU: GeForce 9600 GT

**Comment by anhlt309** [comment]
Results from clinfo command:
CPU Vendor : INTEL
CPU Family : core
CPU Model : i7 860
CPU Gflops : 46.88
CPU Cores :  4

GPU Vendor : NVIDIA
GPU Family : geforce
GPU Model : 9600 GT
GPU Codename : G94a/b
GPU Gflops : 312
GPU OpenCL : 1
GPU Cores-TMU-ROP : 64:32:16
GPU Mem Bandwidth: 57.6
GPU Mem Interface: 256

**Comment by Kees-V** [comment]
I think the issue is that your hardware does not support the Opencl feature set that OpenCV needs. This is not over-documented on the OpenCV pages. There is some information in the [Documentation](http://docs.opencv.org/2.4/modules/ocl/doc/introduction.html)

According to [CPU-boss](http://cpuboss.com/cpu/Intel-Core-i7-860) your CPU does not support OpenCL.
The 8600 GT probably does not support the OpenCL feature set required by OpenCV. On my previous laptop, equipped with nVidia 8600 M, I had similar issues. I only got some (disappointing) results using Cuda.

Please have a try to compile and run "opencv_test_objdetect" which may report more details about the GPU.

**Comment by hamideh8888** [comment]
I have Intel HD graphics and i have OPENCL 1.2, I am using Intel Atom E3845, when I run openalpr with cpu it is really slow, it takes around 6 seconds, So i wanted to enable lbpopencl option in my alpr.config, But unfortunately it is not working I get the following error:
ERROR: can't find OpenCL platform by name:=
ERROR: Requested OpenCL Device not found, check configuration: :=GPU:0
platform:=
Device Types: GPU
Device name: 0
I'm stuck in this issue, any help would be appreciated!

**Comment by Kees-V** [comment]
It looks like the "OPENCV_OPENCL_DEVICE" environment setting is incorrect.
Please run alpr with "debug_detector        = 1" in the config file and check the output to see which opencl devices are available.

Example output:
OpenCL device(s) found:
0 Intel(R) HD Graphics 4600 (OpenCL 1.2 )
1 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (OpenCL 1.2 (Build 10094))
2 Pitcairn (OpenCL 1.2 AMD-APP (2117.9))
3 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (OpenCL 1.2 AMD-APP (2117.9))
....

Set the OPENCV_OPENCL_DEVICE environment variable to
::0 for device 0 (In the example Intel(R) HD Graphics 4600)
::1 for device 1 (In the example Intel(R) Core(TM) i7-4910MQ CPU)
Etc.

**Comment by hamideh8888** [comment]
Thanks a lot Kees, actually I have seen OpenCL device(s) and I have set the environment variable, the only thing that was missing was "debug_detector" that I was missing. I ran openalpr many times but the result didn't change that much. my output in cmd is like image below. 
My guess is my hardware is slow. Also I have downloaded Intel SDK 2016, which supports OpenCL2 (I couldn't find SDK 2013 which supports opencl1.2 on the net ). I have already have the drivers of intel that has opencl dll files, but I didn't have OpenCL libraries so I downloaded SDK 2016. So I have 2 guess, the first is that my hardware is slow and the other is the problem with SDK libraries. Thank you again.
![image](https://cloud.githubusercontent.com/assets/19633211/18035588/63d47c52-6d0d-11e6-830d-941ebc94ddb5.png)

**Comment by Kees-V** [comment]
It's a shame that your HD Graphics does not show up as OpenCL device as it would probably perform better than the CPU. Do you have the latest Intel drivers loaded for the GPU?

The other thing: create a subfolder and add several images with license plates in that folder and run ALPR with the foldername, so it will analyse all the images in one go. You will see that detection in the first image will be slow and subsequent pictures are faster.

**Comment by hamideh8888** [comment]
I did as you said, I created a folder and test openalpr on many images. I found out that the pictures with higher resolution could have processing time around 50ms, but photos with lower resolution(1920*1440) have process time around 2-3 seconds. Also I have the latest available graphic driver installed.  Thanks again Kees.

**Comment by Kees-V** [comment]
Is the HD Graphics listed as an OpenCL device now?

**Comment by hamideh8888** [comment]
yes It has opencl1.2 files

**Comment by Kees-V** [comment]
I would expect to see the GPU listed as third device named HD Graphics.
Performance boost with OpenCL is achieved when using a GPU.

On my computer:
When using OpenCL with the CPU it does not improve performance when compared with direct usage of the CPU (lbpcpu). 
When using OpenCL with the integrated Intel HD Graphics 4600 GPU there is a moderate performance improvement when compared with the direct usage of the CPU (lbpcpu).
When using OpenCL with the discrete AMD GPU there is a big performance improvement when compared with the direct usage of the CPU (lbpcpu).

**Comment by tonystark12** [comment]
@Kees-V Do you mean the following 3 options?

lbpcpu
lbpopencl
lbpgpu

?

**Comment by Kees-V** [comment]
I am sorry, I can't recall what I meant, it's too long ago  :-)
Anyway... you should be able to experiment with the different OpenCL devices available on your computer with the built-in debug options of openalpr.
To do this follow the following instructions (Copy-and-paste from a previous message):

Please run alpr with "debug_detector = 1" in the config file and check the output to see which opencl devices are available.

Example output:
 OpenCL device(s) found:
 0 Intel(R) HD Graphics 4600 (OpenCL 1.2 )
 1 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (OpenCL 1.2 (Build 10094))
 2 Pitcairn (OpenCL 1.2 AMD-APP (2117.9))
 3 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (OpenCL 1.2 AMD-APP (2117.9))
 ....
Set the OPENCV_OPENCL_DEVICE environment variable to
 ::0 for device 0 (In the example Intel(R) HD Graphics 4600)
 ::1 for device 1 (In the example Intel(R) Core(TM) i7-4910MQ CPU)
 Etc.

**Comment by disheet** [comment]
I wrote one code in cpp now I am using gpu so i need to convert it into cuda cpp (nvidia gpu programming).

I am applying ROI to my input video and same thing i wanted to do in CUDA C++. so how i can i apply ROI to my input video. Is there any function available ?
