### ISSUE TITLE
Australia Victoria plate undetectable 

### ISSUE THREAD

**Issue by mikando119** [openalpr/openalpr#200]
hey, 
I'm currently trying to get some Australian plates to work that don't have a conventional style (slim shape attached at bottom) that normal Victorian plate have. at the current moment these plate are not picked up by openalpr by au, us and eu. i was wondering if i need to train the system using ocr  to read the plate or is there more to it that i need to do. i have attached two pictures of the slim plate (don't work) and a single of a normal  (working) plate.   

![vic1](https://cloud.githubusercontent.com/assets/14066184/10010613/14378e20-6131-11e5-9898-d1af2915b19a.PNG) 

![vic2](https://cloud.githubusercontent.com/assets/14066184/10010614/143bd2b4-6131-11e5-9284-49f8907bbff3.PNG)

![vcplate1](https://cloud.githubusercontent.com/assets/14066184/10010619/372baf24-6131-11e5-9c91-adede3540820.png)

thank you for your time,
michael

**Comment by matthill** [comment]
Are the wide ones detected properly when you use the country "auwide"?

**Comment by mikando119** [comment]
sorry late reply. i tied it with the auwide on these images and some normal plates still nothing. should i just play around with the auwide.conf folder in runtime_data?

**Comment by matthill** [comment]
It seems to work reasonably well for me.  I picked two plates from google and they both recognized.  When I run OpenALPR against this wide Victoria rego plate:

![md_aston_martin_v8_vantage_-_black_front_ st_kilda _victoria _australia _11_march_2007](https://cloud.githubusercontent.com/assets/508260/10065199/0b24d124-6250-11e5-9366-fc08147722b3.JPG)

I get: 
plate0: 1 results
    - VAM999	 confidence: 85.0012


When I run agains this one:

![range_rover_evoque_12_f_01_lrg](https://cloud.githubusercontent.com/assets/508260/10065204/2f5799f0-6250-11e5-822f-e29b97723e73.jpg)


plate0: 10 results
    - VRREVQ	 confidence: 86.0546
    - 1VRREVQ	 confidence: 84.3501
    - VRREV0	 confidence: 83.4863
    - EVRREVQ	 confidence: 82.0725
    - 1VRREV0	 confidence: 81.7818
    - E1VRREVQ	 confidence: 80.3681
    - EVRREV0	 confidence: 79.5042
    - VRREVG	 confidence: 79.1588
    - VRREV	 confidence: 78.9625
    - E1VRREV0	 confidence: 77.7998


The Australian training data has a custom trained detector and custom font training for regular sized plates.  The wider plates use the Australian font training and the European style detector since their dimensions are very similar.  It's possible to get even better accuracy by training a detector for the wide plates, but you'd need lots of samples (2000+) to beat the EU style detector.
