### ISSUE TITLE
Is patters file read in runtime?

### ISSUE THREAD

**Issue by gerhardsletten** [openalpr/openalpr#232]
Is the patterns file (on OSX installed here /usr/share/openalpr/runtime_data/postprocess/*) read in runtime, or do you need to restart a service or re-build?

Try to update is for one contry (norway) specifying the regular pattern which is 2 letters and 5 numbers: 

```
no	@@#####
no	@@ #####
```

I use the command line utility 

`alpr -c eu <path to image>`

**Comment by matthill** [comment]
You do not have to rebuild.  Each time alpr is initialized, it will pick up the new patterns.

You must also specify the pattern to use with "-p" -- so your command would be:
alpr -c eu [image] -p no

Also, you don't want to include any spaces in the patterns, since those are removed before patterns are considered.

**Comment by gerhardsletten** [comment]
Thanks!
