### ISSUE TITLE
Nevada Autonomous Vehicle license plates are not recognized.

### ISSUE THREAD

**Issue by sk-** [openalpr/openalpr#240]
Nevada has special licenses for autonomous vehicles (aka self-driving cars). See http://www.dmvnv.com/autonomous.htm for more info.

See the image below:

![Nevada Autonomous Vehicle License Plate](http://robohub.org/wp-content/uploads/2014/07/google_car_nevada_test_license_plate.jpg)

**Comment by matthill** [comment]
I tweaked the config a bit in order to get it to recognize.  Even though we don't have any plates that look exactly like that in the database, it's still close enough to get picked up.

I tweaked the following parameter in us.conf (default is min 4 characters):

    ; Results with fewer or more characters will be discarded
    postprocess_min_characters = 3

And the following parameter in openalpr.conf (default is 1.1):

    detection_iteration_increase = 1.05

The vertical AU is ignored, since we don't have any OCR characters like that, but it's possible to detect that as well if you did OCR training and treated it as a single character.

![goog](https://cloud.githubusercontent.com/assets/508260/11800565/adec78c6-a2ab-11e5-932b-6fc87f066d42.png)
