### ISSUE TITLE
openalpr with gpu (linux)

### ISSUE THREAD

**Issue by fedemarino37** [openalpr/openalpr#305]
Hi, I have a problem with the new version of Alpr (v 2.2.0) compiling with GPU. the version of Opencv is 3.0.0 with CUDA 7.0.

This is the error in Makefile: 
 In file included from /home/visionstudio/Desktop/openalpr/src/openalpr/detection/detectorfactory.h:24:0,
                 from /home/visionstudio/Desktop/openalpr/src/openalpr/alpr_impl.h:33,
                 from /home/visionstudio/Desktop/openalpr/src/openalpr/alpr.cpp:21:
/home/visionstudio/Desktop/openalpr/src/openalpr/detection/detectorcuda.h:34:31: fatal error: opencv2/gpu/gpu.hpp: No such file or directory
 #include "opencv2/gpu/gpu.hpp"
                                                   ^
compilation terminated.

This include comes of Opencv 2.4.11, but this file does not exist in Opencv 3.0.0

Tanks!!

**Comment by matthill** [comment]
Yes, that should be fixable.  Right now I need to support both OpenCV 2 and OpenCV 3 because many distributions haven't upgraded yet.  In the code, you may see a few areas that do something like this:


  #if OPENCV_MAJOR_VERSION == 3
  bg = cv::bgsegm::createBackgroundSubtractorMOG(5, 3, 0.05, 0.0);
  #else
  bg = new BackgroundSubtractorMOG(5, 3, 0.05, 0.0);
  #endif

If you tweak the imports to work with OpenCV 3 and follow the same pattern, I'd be happy to merge it in.

**Comment by anhlt309** [comment]
How to fix this issue? Now I have same problems :(

**Comment by newsages** [comment]
Add:
#define OPENCV_MAJOR_VERSION= TU version

**Comment by newsages** [comment]
I use qt and qmake and use:

QMAKE_CXXFLAGS += -DOPENCV_MAJOR_VERSION=2

**Comment by anhlt309** [comment]
cv::gpu::CascadeClassifier_GPU is not define. How to fix this?

**Comment by matthill** [comment]
You need to compile OpenCV with CUDA/GPU support as well. 
http://docs.opencv.org/2.4/modules/gpu/doc/introduction.html

**Comment by anhlt309** [comment]
Sorry, but i have built with OpenCV 3.1 and seem to dont have gpu module.
Another issue, when i select detector = lbpopencl, the output is OpenCL not detected. Im using card Geforce 9600GT, when i run command: cat /proc/driver/nvidia/version, output is:
NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.96  Sun Nov  8 22:33:28 PST 2015
My OS: Centos 7
