### ISSUE TITLE
The manipulations for  high-constrast situation in edgefinder.cpp may cause some probelm

### ISSUE THREAD

**Issue by SunAriesCN** [openalpr/openalpr#306]
I just read your codes about the manipulations for high-constrast. And I think that process can not lead your result to better accuracy for low-contrast situation, even get the worse consequence in high-contrast. Because the plate lines are easy to be found in high-constrast croped-image after the first transformation step, and the lines are always good. However you just extend the crop area without the first step transformation, especially the rotation,  leading the good plate lines  to be eliminated  easily in plate corner finding part. I want to know what do you think about this part?

**Comment by matthill** [comment]
I added that feature based on a particular user having lower success rate with their high-contrast images.  They sent me about 500 plates that were tagged and I used those to benchmark.  After adding the feature, accuracy increased fairly significantly (~12%).  I also ran it against my standard benchmarks for EU and US plates and the accuracy did not change in a significant way.

The biggest issue with the high-contrast plates was that the letters themselves were being treated as edges.  A "1" character, for example, may be seen as an edge, since it adds a tall, dark line across the plate.  However, when we zoom out a bit and look for large blocks of white rectangular areas, it tends to do a much better job of filtering that out and finding the correct edges.

I'm open to suggestions, I'm sure there are better ways to do it.  Perhaps my benchmarks are not capturing the effect adequately.  This config option can be tweaked to a higher number (e.g., 10.0) which would effectively turn the feature off:
https://github.com/openalpr/openalpr/blob/master/config/openalpr.conf.in#L58

**Comment by SunAriesCN** [comment]
Can I have your 500 plates which is high-contrast.

**Comment by matthill** [comment]
Sorry for the delay.  I asked permission to release them, but I was told no.  Here's generally what those images look like: 
https://github.com/openalpr/openalpr/issues/260

If you send me your e-mail (mine is matthill@openalpr.com), I have a few images from a different source (~50 images) that are similar night-time high contrast shots that I can send you.

**Comment by SunAriesCN** [comment]
Hey matthill, I have sent you a mail, and I'm waiting for your reply there.

**Comment by SunAriesCN** [comment]
Thanks for your email and images, I have looked through all them, and reviewed the codes about that part. And I'm sorry that I just found I have missed your highConstrastDetection function, when I read your codes of that part again. I think your process maybe good enough for the darklight situation, but  another headache  of this part for me is that Chinese character would have the same problem as your "1" in daylight, because the situation outside the plate is still complicated. I'm trying to deal with it for my research, and I will close this issue soon.
