### ISSUE TITLE
U.S. issue with "2" being considered "Z"

### ISSUE THREAD

**Issue by pablofernandezcom** [openalpr/openalpr#307]
Is anyone else facing this issue?

Occurred on Open ALPR Cloud Platform.

<img width="676" alt="screen shot 2016-03-18 at 11 02 33 pm" src="https://cloud.githubusercontent.com/assets/17712306/13897017/d8f8b392-ed5e-11e5-92b0-af276ae27d7b.png">

**Comment by matthill** [comment]
I believe this is due to the California pattern matching.  OpenALPR has detected that it's a california license plate, and has applied the California template to it.  Below are the results.  You'll notice the first result is the correct number, but because it thinks it's a California plate, it matches it against those patterns.  The third one on the list (#@#####) is what matches.  How common are these 7 number plates in California?  If it's less than 2% or so, it's probably better to leave them off the patterns.  Otherwise, we should add it.

```
ca		#@@@###
ca		#@@@###
ca		#@#####
ca		#####@#
ca		###@@@
```

```
[mhill@mhill-linux tmp]$ alpr d8f8b392-ed5e-11e5-92b0-af276ae27d7b.png -p ca
plate0: 10 results
    - 1291164	 confidence: 93.2607	 pattern_match: 0
    - 1Z91164	 confidence: 85.6086	 pattern_match: 1
    - I291164	 confidence: 80.8168	 pattern_match: 0
    - 1291I64	 confidence: 80.4712	 pattern_match: 0
    - 129I164	 confidence: 79.8852	 pattern_match: 0
    - IZ91164	 confidence: 73.1647	 pattern_match: 0
    - 1Z91I64	 confidence: 72.8191	 pattern_match: 0
    - 1Z9I164	 confidence: 72.2331	 pattern_match: 0
    - I291I64	 confidence: 68.0274	 pattern_match: 0
    - I29I164	 confidence: 67.4413	 pattern_match: 0

```
