### ISSUE TITLE
How to properly use classifychars?

### ISSUE THREAD

**Issue by yaftkoldo** [openalpr/openalpr#309]
I'm following the instructions here: http://doc.openalpr.com/accuracy_improvements.html#producing-tiles-from-actual-plates

When I run the program with the needed parameters, the "Original" and "Selection dashboard" windows open. P and N both do what they appear to be intended to. However, when I press enter, nothing happens. Nothing also happens, when I try to use the arrow keys to select a rendering, it only says "Did not select and boxes" and does nothing, or, says "You have not tagged any characters" if I've already pressed space. Pressing w does nothing. Pressing space changes the green outline to blue, but nothing else happens. Pressing s results in "You have not tagged any characters" or "Did not select any boxes" based on whether or not I've pressed space. 

I'm sure I'm missing something obvious, but I cannot figure it out. Any help?

**Comment by matthill** [comment]
The enter key probably isn't firing in the code.  This utility is built in simple OpenCV (rather than something more sophisticated like QT) so it's virtually impossible to get the key mappings right for all the different keyboard localities and operating systems.  If you look at the value going into "waitKey" in the code, you may see what's wrong.  It's probably looking for the enter key on the wrong value.

What should happen, when you press enter, it brings up a smaller window that you can use to tag the individual characters.  Then, afterwards, you can press space to select the boxes that you want to extract characters for.

**Comment by yaftkoldo** [comment]
@matthill that makes sense. Do you know if it uses the codes that the keyboard sent, or some other, higher level codes? If it's just that, I can use showkey and put in the proper scan codes, and recompile.

**Comment by matthill** [comment]
If you add:
cout << waitkey << endl;

right after this line: https://github.com/openalpr/openalpr/blob/master/src/misc_utilities/classifychars.cpp#L179

That should show you what key you're pressing.  Then it's comparing it to the ENTER_KEY_ONE and ENTER_KEY_TWO value.  If you change that to match the number printed to the console, it should work.

**Comment by yaftkoldo** [comment]
@matthill thanks! I got it to work. For others with this problem, these are the values I had to use (On Ubuntu):

```
const int LEFT_ARROW_KEY = 65361;
const int RIGHT_ARROW_KEY = 65363;

const int DOWN_ARROW_KEY = 65364;
const int UP_ARROW_KEY= 65362;

const int ENTER_KEY_ONE = 10;
const int ENTER_KEY_TWO = 1048586;

```
Note that they are NOT the same as the keyboard scan codes gotten using the showkey command

**Comment by jkjung-avt** [comment]
On my Ubuntu 16.04 (x86_64) system, I had to use the following values to get it to work.

    const int LEFT_ARROW_KEY = 81;
    const int RIGHT_ARROW_KEY = 83;

    const int DOWN_ARROW_KEY = 84;
    const int UP_ARROW_KEY= 82;

    const int ENTER_KEY_ONE = 13;
    const int ENTER_KEY_TWO = 10;

**Comment by nhtoan611** [comment]
Forgive me, I guess it might be a silly question.
I got the same issue so I put many `cout` to check for `waitkey`, but the problem was I couldn't manage to recompile to test it. I tried `cmake ./ `and `make` but it didn't work. Any advice?

**Comment by jkjung-avt** [comment]
I documented how I compiled openalpr here.

https://jkjung-avt.github.io/openalpr-on-tx2/

'openalpr-utils-classifychars' should be built along with 'alpr' when you do 'make'.

**Comment by jkjung-avt** [comment]
By the way, the `cout` statement should be put after this line instead.

https://github.com/openalpr/openalpr/blob/master/src/misc_utilities/classifychars.cpp#L288

**Comment by nhtoan611** [comment]
@jkjung-avt thank you it was so helpful. I made it

**Comment by jnxyatmjx** [comment]
@jkjung-avt   thanks it is helpful. but i can't save chinese characters into the outdirs? do you konw why?

**Comment by jkjung-avt** [comment]
I haven't looked deeper into that. But since the 'classifychars.cpp' was designed to save each cv::waitKey() keycode as a character, it's understandable it wouldn't work for Chinese characters.

If you don't plan to re-write a big portion of 'classifychars.cpp', the best solution is probably to save Chinese character picture crops with some special token first. And then manually change file names afterwards......

**Comment by losabio1617** [comment]
Sir @jkjung-avt  after i copy what should i do?? 
(test) losabio@losabio-System-Product-Name:~/env/openalpr/src/build/misc_utilities$ openalpr-utils-classifychars ph WINPUT WOUT
Usage: 
	n		-- Next plate
	p		-- Previous plate
	W		-- Select image and save characters according to OCR results, then go to next image
	s		-- Save characters
	<- and ->	-- Cycle between images
	Ent/space	-- Select plate

Within a plate
	<- and ->		-- Cycle between characters
	[0-9A-Z]		-- Identify a character (saves the image)
	ESC/Ent/Space	-- Back to plate selection
WINPUT/phplate1.png
OCR results: AAC1226
You have not tagged any characters
Did not select any boxes
Did not select any boxes
Did not select any boxes
Did not select any boxes
Did not select any boxes

**Comment by jkjung-avt** [comment]
Refer the 'classifychars' section in the [documentation](http://doc.openalpr.com/opensource.html?highlight=classifychars).  Otherwise, you might need to read the source code to understand how to use it.

It's been quite a while since the last time I work on openalpr.  I think I'm not be able to provide much more help on this matter.

**Comment by losabio1617** [comment]
I already done it sir thanks for the reply i edit na classifychar.cpp with
the following value of arrow keys but i have a new problem , selection of
character to generate ttf i dont know where to select char position

**Comment by losabio1617** [comment]
@jkjung-avt  i have this infinite loop idk where it came from 
![screenshot from 2019-01-16 22-43-12](https://user-images.githubusercontent.com/38846946/51294254-270c5880-19e0-11e9-8641-0c0fea25fb79.png)

**Comment by losabio1617** [comment]
it keeps looping into 255 that might be cause closing the selection of character

**Comment by alucard079** [comment]
I'm classifying the characters of a plate number using the "classifychars" utility, after running that some window will open like the "Selection Dashboard" and you will choose and highlight the plate number in 3 copies of plate number, then there's something must be open the "Character Selector" But I can't do that because it closes automatically, and I though my keys are correct and there's an infinite loop printing "key: 255"

Currently, I am using Linux Ubuntu 18.04, running with Python 3 and OpenCV 3 and tesseract 3. I'm about to make a tiles in every plate numbers that I input. I suspect, that's why the "Character Selector" closes automatically because there's a key that has been continuously pressing which is not corresponding or meeting the condition in opening the "Character Selector".

This is the classifchars.cpp from line 41-75

`#ifdef __APPLE__
const int LEFT_ARROW_KEY = 2;
const int RIGHT_ARROW_KEY = 3;

const int DOWN_ARROW_KEY = 1;
const int UP_ARROW_KEY= 0;

const int ENTER_KEY_ONE = 13;
const int ENTER_KEY_TWO = 10;

#elif WIN32
const int LEFT_ARROW_KEY = 2424832;
const int RIGHT_ARROW_KEY = 2555904;

const int DOWN_ARROW_KEY = 2621440;
const int UP_ARROW_KEY = 2490368;

const int ENTER_KEY_ONE = 13;
const int ENTER_KEY_TWO = 10;
#else
const int LEFT_ARROW_KEY = 81;
const int RIGHT_ARROW_KEY = 83;

const int DOWN_ARROW_KEY = 84;
const int UP_ARROW_KEY= 82;

const int ENTER_KEY_ONE = 13;
const int ENTER_KEY_TWO = 10;
#endif

const string SPACE = " ";
const int SPACE_KEY = 32;
const int ESCAPE_KEY = 27;

const int DASHBOARD_COLUMNS = 3;`

This is the classifychars lines 288-289, which print the keycode of what you are pressing and display in cmd.

`waitkey = waitKey(50);
          std::cout << "key: " << (int) waitkey << std::endl;`

I expect the output to select and to make it stay the Character Selector and select every character in plate number. After selecting the character, I can press the "s" with that it will save the character that I selected from Character Selector.

![screenshot from 2019-01-24 16-06-56](https://user-images.githubusercontent.com/28977709/51686270-0de05900-202b-11e9-93d1-070e163ab769.png)

**Comment by Andreskammerath** [comment]
Hi @alucard079 I had the same issue, and I had resolved it adding && waitkey != 255 in line 361, the else if statement is like above now:
```cpp
else if (waitkey > 0 && regex_rule.match(utf8chr(waitkey)) && waitkey != 255 ) // Verify that it's an actual character
```
