### ISSUE TITLE
Install overwrites existing configs

### ISSUE THREAD

**Issue by nayrnet** [openalpr/openalpr#343]
the empty configuration files should not overwrite existing files when installed, especially now that defaults and new options can be updated in the default config file.

**Comment by matthill** [comment]
That is the intention.  The files in /etc/openalpr/[alprd.conf, openalpr.conf] are no longer going to be changed by the installers.  We'll just manage the default config files in /usr/share/openalpr/config.

Are you seeing a case where it's doing something different?

**Comment by nayrnet** [comment]
yeah, when I run make install both the files /etc/openalpr/[alprd.conf, openalpr.conf] are overwritten and replaced with the empty files.. lost my configuration after updating.

**Comment by matthill** [comment]
I see.  I think that's expected behavior.  'make install' will always copy all packaged files.  The reason we're using empty configs is to be more friendly with package managers (e.g., Debian/Ubuntu deb/apt and RedHat yum/rpm).  The default configs will be replaced on upgrades, but the user configs (in /etc/openalpr/) will never be touched.
