### ISSUE TITLE
C# Intagration bug

### ISSUE THREAD

**Issue by Hupiter** [openalpr/openalpr#349]
I am sending frames using c# via: Alprnet.Recognize(Bitmap(Picture)) it seems to work fine but after 1 minute sending frames it stops recognizing, it's seems to receive pictures but never give another plate.
Always stop after one minute.
version openalpr 2.2

I found out that the openalpr library is only giving results for 129 frames and then stop, Is this some kind of bug or is a licensing problem?

**Comment by Jeferson-Oliveira** [comment]
Hello, can you up your project in github?

**Comment by newsages** [comment]
Memory stack full?   If you use temps cv::Mat emember clean cv::Mat::release();

**Comment by Hupiter** [comment]
I don't have same problem with older openalpr version I tried to migrate to 2.2 and this happend.

**Comment by Hupiter** [comment]
is not a library issue so I need to review my code, thanks for everything.

**Comment by jovargas** [comment]
Hi @Hupiter !!
I'm facing the same problem here. Did you find any solution??
I've created a disposable object too for detection and I was afraid this could lead me to the problem, but since there is no error message from the library, I'm not able to figure out what am I doing wrong. 
I'll appreciate any help. Thanks!!
