### ISSUE TITLE
OpenAlpr Net Build Accuracy

### ISSUE THREAD

**Issue by dmcspadden** [openalpr/openalpr#384]
First, this project is amazing - what a great community around it!

I've been playing with the .NET wrapper in my application - reading from a live stream.  It's very fast (even with 15fps 720p video).  And, it's really accurate *most* of the time.  However, about 25% of the time the plate is wildly inaccurate with a relative high confidence (70%+).  If I take the exact image (which I save off in my app) and run it through the CLI it returns the proper match with an even higher confidence.

Is there something unique to the .NET wrapper build that would lead to different results?

**Comment by steffkes** [comment]
I have no idea, if the comment does apply here as well .. but it sounds a little bit like it?

> Yes, I've noticed there's some state stored in the OpenCV LBP detector. When you initialize from scratch, results are always deterministic, but when you run one after another (e.g., reading all images in a directory, or a video stream) there's some randomness.
-- https://github.com/openalpr/openalpr/issues/358#issuecomment-225392536

**Comment by matthill** [comment]
Yes, that's right.  The detector returns slightly different results when it's reused rather than from a cold start.  Even a few pixels changing can alter the results.

You can set this parameter: https://github.com/openalpr/openalpr/blob/master/config/openalpr.conf.defaults#L59

Which runs the process multiple times per image.  This gives you a higher chance of getting the correct plate, at the cost of slower processing speed.

**Comment by dmcspadden** [comment]
Thanks for the help guys!

I think rather than simply run everything through twice by setting that option – I may add another post-processing step to “audit” the results.  That way I don’t slow down processing and risk missing another plate.

Thanks again for all you guys do!
