### ISSUE TITLE
Detect multiline and singleline EU plates with single instance

### ISSUE THREAD

**Issue by bradcagle** [openalpr/openalpr#390]
Is it possible to support multiline and singleline EU plate detection with a single instance of Alpr()?
Or do I need to run two instances with two separate config files?

Also Is the multiline EU plate detector complete now, or is it still short on training data?

Thanks

**Comment by matthill** [comment]
The library supports multiline, but we still haven't collected enough multilines plates to make a decent detector.

**Comment by matthill** [comment]
To answer your first question, yes it can run both detections in one instance.  Use a comma when specifying the country (e.g., eu,eu2).

**Comment by newsages** [comment]
But is on sequential order or parallel?

**Comment by shivam6294** [comment]
@matthill Would using two detectors take roughly twice as long in terms of compute time? Or is the detection done in parallel?

**Comment by zhouhao27** [comment]
@matthill I managed to make the double line works for Singapore vehicle plates. But it's not always accurate. Actually the accuracy is quite low. At first I though it's because of the detector training is not enough. I only have 900 images for the training. But I tried to skip the detection by setting this in openalpr.conf:

> skip_detection = 1

And manually cut the images so that they only contains the vehicle plates part. The result is still not good. Any suggestion?
