### ISSUE TITLE
detector missing characters

### ISSUE THREAD

**Issue by ChillyGuy** [openalpr/openalpr#422]
Hello!
Im working on training alpr for Iranian plates, theres a problem which is bugging me ever since i started my custom ocr traineddata against plates.

for some reason some characters are not detectable by the program and I'm clueless how to fix it.
as an example in screen shot below plate on the right has 8 characters but ALPR detects only 7 funny thing is it has detected it correctly but for some reason demoted the result to the second place ... (correct result has confidence : 79.8315)

![result](https://cloud.githubusercontent.com/assets/14247111/20299192/0f3b1038-ab2f-11e6-82c4-9ad200f6d29a.png)

<img width="1440" alt="Plate example" src="https://cloud.githubusercontent.com/assets/14247111/20298816/391b60a8-ab2d-11e6-82ac-83c09334f822.png">

[debug.txt](https://github.com/openalpr/openalpr/files/591456/debug.txt)

Thanks in advance

**Comment by matthill** [comment]
That's because it didn't strongly match the first "9" character.  It was more confident that it wasn't sure what it was:

Improving the quality of the OCR training set may help

PostProcess Line 0 Letter: 0 ۲ -- score: 137.066 -- occurrences: 6
PostProcess Line 0 Letter: 0 ۳ -- score: 9.24496 -- occurrences: 1
PostProcess Line 0 Letter: 0 ~ -- score: 5.75504 -- occurrences: 1
PostProcess Line 0 Letter: 1 ۲ -- score: 134.638 -- occurrences: 6
PostProcess Line 0 Letter: 2 و -- score: 73.7063 -- occurrences: 6
PostProcess Line 0 Letter: 2 ~ -- score: 33.014 -- occurrences: 5
PostProcess Line 0 Letter: 2 ۶ -- score: 1.49072 -- occurrences: 1
PostProcess Line 0 Letter: 3 ۵ -- score: 113.704 -- occurrences: 6
PostProcess Line 0 Letter: 4 ۳ -- score: 75.3051 -- occurrences: 6
PostProcess Line 0 Letter: 4 ~ -- score: 41.1455 -- occurrences: 10
PostProcess Line 0 Letter: 4 ۲ -- score: 28.5798 -- occurrences: 3
PostProcess Line 0 Letter: 4 ۴ -- score: 4.96964 -- occurrences: 1
**PostProcess Line 0 Letter: 5 ~ -- score: 18.8806 -- occurrences: 2
PostProcess Line 0 Letter: 5 ۹ -- score: 11.1194 -- occurrences: 2**
PostProcess Line 0 Letter: 6 ۹ -- score: 70.4581 -- occurrences: 6
PostProcess Line 0 Letter: 6 ~ -- score: 22.4862 -- occurrences: 4
PostProcess Line 0 Letter: 7 ۹ -- score: 62.8051 -- occurrences: 4
PostProcess Line 0 Letter: 7 ~ -- score: 4.51016 -- occurrences: 2

**Comment by ChillyGuy** [comment]
Hello Mat,
Thanks for responding i'll try to improve ocr library.

**Comment by mrht74** [comment]
Hello dear \@ChillyGuy , I
m working on persian alpr , did u got any result , i need some help

**Comment by ChillyGuy** [comment]
Hey,
Yep, it takes a bit time to get the hang of it but once you do you can get it to work.

**Comment by zongoalbert** [comment]
hello dear @ChillyGuy 

I'm working on a project about recognizing moroccan license plates which look like this image :
![image](https://user-images.githubusercontent.com/55978810/76768128-dedef680-679a-11ea-893b-40aac8be2c0e.png) 
i did not have datasets , i decide to use "us" and "eu" alpr
i tried to modify "us.patterns"   i added the line " mr              #####@# "

When I run the command line " alpr -p mr lprmr.jpg"  it
give me this result :

plate0: 8 results
    - 4316 confidence: 83.3094 pattern_match: 0
    - 43I6 confidence: 76.1957 pattern_match: 0
    - 431B confidence: 68.5094 pattern_match: 0
    - 431G confidence: 67.8764 pattern_match: 0
    - 431S confidence: 64.9272 pattern_match: 0
    - 43IB confidence: 61.3957 pattern_match: 0
    - 43IG confidence: 60.7626 pattern_match: 0
    - 43IS confidence: 57.8135 pattern_match: 0
![image](https://user-images.githubusercontent.com/55978810/76768805-d33fff80-679b-11ea-8810-132b2431b415.png)
![image](https://user-images.githubusercontent.com/55978810/76769127-4f3a4780-679c-11ea-847b-eedb53f4e214.png)
NB :Morrocan lpr like  Iran lpr both of theme have one arabic letters in the middle ,
PLease sir help me.
Best regard.
