### ISSUE TITLE
Error, Could not find/load native library (libopenalprc.dll) C#

### ISSUE THREAD

**Issue by dawigak** [openalpr/openalpr#430]
HI, when i am trying to read a image, i am getting this error

Exception thrown: 'System.DllNotFoundException' in alprnet.dll
Could not find/load native library (libopenalprc.dll)
Exception thrown: 'System.DllNotFoundException' in alprnet.dll
Exception thrown: 'System.DllNotFoundException' in alprnet.dll
The thread 0x1a60 has exited with code 0 (0x0).
The thread 0x29d0 has exited with code 0 (0x0).

i am trying to find this DLL(libopenalprc.dll) but not luck yet, can you help me please?

**Comment by matthill** [comment]
The libopenalprc binary was added in 2.4.0.  We haven't compiled binaries for that release for Windows yet.  You can compile it yourself following the guides, or you can pull an older version of the .NET integration which works with the older OpenALPR lib.

**Comment by dawigak** [comment]
thank you so much, it worked

**Comment by mustang61** [comment]
dawigak how to solved your problem. i cant compile solution can you explain it

**Comment by alciomarhollanda** [comment]
Where i find libopenalprc.dll? I have version 2.3.0 .

"Unable to load DLL 'libopenalprc.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

**Comment by alciomarhollanda** [comment]
Not have yet ?

**Comment by dammikapw** [comment]
Hi matthill,
First of all thank you very much for sharing this project with us. 
I'm also getting same error when i'm trying to run C# sample project. I couldn't find the required DLL(libopenalprc.dll). You mentioned that it can be found in 2.4.0 and you haven't compiled binaries for that release. But where is 2.4.0? I could find only 2.3.0 as the latest release. Please help me in this. Thanks in advance.
@
Exception thrown: 'System.DllNotFoundException' in alprnet.dll
Could not find/load native library (libopenalprc.dll)
Exception thrown: 'System.DllNotFoundException' in alprnet.dll
Exception thrown: 'System.DllNotFoundException' in alprnet.dll

**Comment by saduncem** [comment]
Is there anyone ?

**Comment by jmanuelsoberano** [comment]
Has someone already got libopenalprc.dll ??

**Comment by lucassrfreire** [comment]
Hi @matthill . Where can we find the 2.4.0 to compile it? An how pull an older version of the .NET integration which works with the older OpenALPR lib?

Thanks for the project!

**Comment by dotnetsqlcoder** [comment]
useless

**Comment by infojess** [comment]
**### look my friends:**
https://github.com/infojess/OpenAlpr_C-_example

**Comment by Stark16** [comment]
I am using Openalpr v2.8.1 and still can't import `libopenalpr.dll`. I know it exists in the base build directory but `test.py` is unable to run because I get the following error:

`FileNotFoundError: Could not find module 'libopenalpr.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

I have added this directory to `PATH` and also tried using `os.add_dll_directory(<path to the dll>)` as suggested [here ](https://stackoverflow.com/questions/64178461/error-when-trying-to-run-openalpr-in-python)

I have also read that the above error can arise because the `libopenalpr.dll` itself imports other `dlls` as mentioned [here](https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found)

I am using python `3.8.5` `x64`
