### ISSUE TITLE
how disable ocr in c# binding 

### ISSUE THREAD

**Issue by vio17** [openalpr/openalpr#494]
hi
I just want to use plate rectangle detection , and not ocr.
how can I disable ocr in c# binding ?

**Comment by jovargas** [comment]
You don't need to disable OCR in C# binding. Just ignore the OCR result and get the plate coordinates to do what you want.
However, I'd recommend to implement a basic object detector using OpenCV Cascade Classifer and the .xml's from OpenALPR. 

You can use EmguCV instead (OpenCV wrapper for C#) 
http://stackoverflow.com/questions/28415161/how-to-load-a-cascadeclassifier-using-emgu-c-sharp
https://github.com/emgucv/emgucv

**Comment by vio17** [comment]
wow , thanks alotttttttttt <3
that was great ... 
but there is a little bit problem with Cascade Classifier , I made it to detect plates . but it's output ( from DetectMultiScale method ) is array of rectangles , how can I find the coordinates of plate's corners , in the case that plate is rotated .
in this code : 
`var results = malpr.Recognize(ms);`
I can find coordinate of plate's corner in 
`result[0].PlatePoints`
but how can I access them in "DetectMultiScale"'s output ?

**Comment by jovargas** [comment]
Hi vio17... First of all, please mark this topic as closed since it's not an issue but actually a question.

Well, if you really need the plate coordinates, then use OpenALPR ignoring OCR result as I mentioned before. OpenALPR uses advanced CV methods to find best plate candidate in every rectangle obtained from the cascade classifier (dewarping, finding corners, etc). 

The detection goal is to have rectangles containing only plates (true positives). What I mean is, one rectangle per plate in the image. If you have rectangles with no plates (false positives) that means the detector sensibility is too high or its accuracy is not as good as expected and you need to train it more.

**Comment by vio17** [comment]
thank you very muchhhh .. 
sorry because of asking question here .
but would please help to locate the codes of "finding corners" in openalpr source ?
may I learn that , thanks again

**Comment by jovargas** [comment]
https://github.com/openalpr/openalpr/blob/master/src/openalpr/edges/platecorners.cpp

Good luck!
