### ISSUE TITLE
Error Run in JAVA, Python , C#

### ISSUE THREAD

**Issue by alciomarhollanda** [openalpr/openalpr#521]
Hello, i would like run test.py, but show erro "test.py: error: too few arguments".

What's arguments i need to set ? 

I have python 2.7

![image](https://user-images.githubusercontent.com/5420987/27284725-5ffccd4a-54d0-11e7-9821-a5b8467fc151.png)

I tried run in java too, by i don't know because show erro.

![image](https://user-images.githubusercontent.com/5420987/27285095-d6433e20-54d1-11e7-95d3-21906f8aed47.png)

And C# too

![image](https://user-images.githubusercontent.com/5420987/27285175-20eceae8-54d2-11e7-8e1d-9ef1b4b6ab41.png)

Have some step and step ?

**Comment by alciomarhollanda** [comment]
I tried run the exemplate java but show too

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\alciomar.hollanda\Downloads\2.3\openalprjni.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.openalpr.jni.Alpr.<clinit>(Alpr.java:7)
	at Main.main(Main.java:15)
C:\Users\alciomar.hollanda\AppData\Local\NetBeans\Cache\8.2\executor-snippets\debug.xml:83: Java returned: 1
BUILD FAILED (total time: 2 seconds)

**Comment by jovargas** [comment]
It's everything clearly explained on the error logs. You need to pass the arguments in Python and Java:
Looks like you are brazilian, so try something like this:
Pyhton
**-c br --config C:\PastaContendoDLLs\openalpr.conf --runtime_data C:\Users\alciomar.hollanda\Desktop\ALPR\openalpr\src\runtime_data C:\QualquerPasta\imagemComPlaca.jpg**

Java
**br C:\PastaContendoDLLs\openalpr.conf C:\Users\alciomar.hollanda\Desktop\ALPR\openalpr\src\runtime_data C:\QualquerPasta\imagemComPlaca.jpg**

For C#, you need to compile the OpenALPR's latest source code and then add the libopenalprc.dll to your binding folder. If you are not able to compile it, then use the v2.3.0 release that implements an older (but stable) version of C# binding.

In ALL cases, openalpr.dll and its dependencies (opencv and leptonica) should exist in your binding folders because they are made to, well, "bind" to the native instance. That should solve the last Java error you commented about.
