### ISSUE TITLE
Silly Question - Can openalpr be used to read electricity meter reading? 

### ISSUE THREAD

**Issue by muthumani-prabhu** [openalpr/openalpr#580]
My sincere apologies to raise this kind of silly question, but still I am more interested in finding out the possibility of using openalpr for electricity meter reading.

Would appreciate, if anyone could lend their helping hands on the possibilities

Thank you very much
mani

**Comment by chathurangac** [comment]
In theory you cannot. OpenALPR comes with more stages such as plate detection stage which is not actually required for your purpose.

It will be much efficient to write a one with OpenCV your self rather than trying to modify the OpenALPR code. A good starting point would be : [Recognizing Digits with OpenCV](https://www.pyimagesearch.com/2017/02/13/recognizing-digits-with-opencv-and-python/)

**Comment by muthumani-prabhu** [comment]
Learned that, it is not possible to use openalpr for electricity meter reading. Hence closed this issue. I am still working on the meter reading part, If I get any references, I can post it in the comment.

**Comment by gitrago** [comment]
@muthumani-prabhu Hi Mani, 

have you found any open source libs for this task or anything other than anyline.io ?

**Comment by chrisxue815** [comment]
https://pixometer.io/ looks decent too.
