### ISSUE TITLE
some problem in findOuterBoxMask

### ISSUE THREAD

**Issue by alimirzaei** [openalpr/openalpr#81]
Hi,
I am trying to understand what really has been done in findOuterBoxMask function. I have some problem with this part of code : 
for (unsigned int i = 0; i < contours[winningIndex].size(); i++)
      {
        for (unsigned int j = 0; j < contours[winningIndex].size(); j++)
        {
          if (contours[winningIndex].hierarchy[j][3] == winningParentId)
          {
            double arclength = arcLength(contours[winningIndex].contours[j], false);
            if (arclength > longestChildLength)
            {
              longestChildIndex = j;
              longestChildLength = arclength;
            }
          }
        }
      }

What is the functionality of outer loop (i loop) here? It seems that the same procedure runs at each iteration!!! the inner block dose not depend on loop variable (i) at all!!!

**Comment by matthill** [comment]
That whole section of code can be removed.  That is some vestigial code that didn't work out.  I was trying to solve an issue where the characters were touching the edge of the plate (typically happens when using vanity covers).  It didn't work, but I didn't remove all of the code.

Resolved in commit e4880f57f1e2bd586aca522db5e9d6d552aab46d
