### ISSUE TITLE
Unable to compile due to undefined references on Fedora

### ISSUE THREAD

**Issue by tmscer** [openalpr/openalpr#846]
My system is Fedora, I followed the install instructions at https://github.com/openalpr/openalpr/wiki/Compilation-instructions-(Fedora-Linux). However, command **make** fails due to the following error:

> [ 53%] Linking CXX executable alprd
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQsetNoticeProcessor@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQputCopyEnd@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQftype@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `lo_read@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQgetResult@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQclear@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `lo_open@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQntuples@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQconnectdb@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQescapeStringConn@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQresultStatus@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQgetlength@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQfinish@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQerrorMessage@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQnfields@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQfname@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQftable@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQftablecol@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `lo_close@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQfmod@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQexec@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQsetClientEncoding@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `lo_write@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQexecParams@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQcmdStatus@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQstatus@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQgetvalue@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQgetisnull@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `lo_creat@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQputCopyData@RHPG_9.6'
/usr/bin/ld: //usr/lib64/libgdal.so.20: undefined reference to `PQresultErrorMessage@RHPG_9.6'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/alprd.dir/build.make:185: alprd] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/alprd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Any ideas on what I may be missing or how to proceed?

**Comment by tmscer** [comment]
The issue seems to be unrelated to OpenALPR.

**Comment by jjerphan** [comment]
I reopen this issue because I had a similar problem when trying to compile [ttk](https://github.com/topology-tool-kit/ttk) on Fedora 30.

Here is a similar stack trace I got when compiling:
```
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQfname@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQresStatus@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQftype@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQexec@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQfformat@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQclear@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQntuples@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQstatus@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQconnectdb@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQescapeStringConn@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQgetvalue@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQgetisnull@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQresultStatus@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQfinish@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQerrorMessage@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQnfields@RHPG_9.6'
/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1: undefined reference to `PQresultErrorMessage@RHPG_9.6'
```

Though some symbols were referenced when inspecting the library `/usr/bin/ld: /usr/lib64/vtk/libvtkIOPostgreSQL.so.1` (this can be inspected with `objdump`, `readelf` or `nm`, see the bottom of this comment) it seems that this was rather due to missing a library version within `libpg`:
```bash
$ ldd /usr/lib64/vtk/libvtkIOPostgreSQL.so.1             
/usr/lib64/vtk/libvtkIOPostgreSQL.so.1: /usr/pgsql-12/lib/libpq.so.5: no version information available (required by /usr/lib64/vtk/libvtkIOPostgreSQL.so.1)
# ... 
	libpq.so.5 => /usr/pgsql-12/lib/libpq.so.5 (0x00007fa9b39c0000)
# ...
```

On my machine, this latter version was provided by several `devel` packages for PostGreSQL 12, namely:
```bash
$ dnf provides /usr/pgsql-12/lib/libpq.so
postgresql12-devel-12rc1-2PGDG.f30.x86_64 : PostgreSQL development header files and libraries
Repo        : pgdg12
Matched from:
Filename    : /usr/pgsql-12/lib/libpq.so

postgresql12-devel-12.0-1PGDG.f30.x86_64 : PostgreSQL development header files and libraries
Repo        : @System
Matched from:
Filename    : /usr/pgsql-12/lib/libpq.so

postgresql12-devel-12.0-1PGDG.f30.x86_64 : PostgreSQL development header files and libraries
Repo        : pgdg12
Matched from:
Filename    : /usr/pgsql-12/lib/libpq.so

# ...
``` 
I uninstalled them  and it resolves my problem:
```
$ sudo dnf erase postgresql12-devel-12.0-1PGDG.f30.x86_64
$ sudo dnf erase postgresql11-libs-11.5-1PGDG.f30.x86_64
$ sudo dnf erase postgresql12-libs-12.0-1PGDG.f30.x86_64
# ...
```

--- 

@tmscer : you might want to try commands like those ones to inspect your library, `/usr/lib64/libgdal.so.20`:

```bash
$ objdump -gC /usr/lib64/libgdal.so.20
$ objdump -g /usr/lib64/libgdal.so.20
$ readelf -Ws /usr/lib64/libgdal.so.20 | grep '^\([[:space:]]\+[^[:space:]]\+\)\{6\}[[:space:]]\+[[:digit:]]\+'
$ nm --demangle --dynamic /usr/lib64/libgdal.so.20
```

**Comment by vdukhovni** [comment]
I solved the same issue on a Fedora 31 system by:
```shell
# rm /etc/ld.so.conf.d/postgresql-pgdg-libs.conf
# ldconfig /usr/lib64
```
The reason for the warnings is that Postgres installs two versions of `libpq`, one in `/usr/pgsql-12/lib` and another in `/usr/lib64`:
```
$ rpm -qfi /usr/lib64/libpq.so.5.12 /usr/pgsql-12/lib/libpq.so.5.12  | pcregrep '^(Name|Version|Release)'
Name        : libpq
Version     : 12.2
Release     : 1.fc31

Name        : postgresql12-libs
Version     : 12.2
Release     : 2PGDG.f31
```
And with the custom `ld.so.conf` snippet which contains `/usr/pgsql-12/lib/` the preferred `libpq` ends up being the version-specific one in `/usr/pgssql-12`.  But since the executables in /usr/pgsql-12/bin all have explicit RUNPATH settings, and almost everything else on the system expects the "generic" library from `/usrlib64`, the custom `ld.so.conf` setting is counter-productive.

```
$ readelf -d /usr/pgsql-12/bin/psql | pcregrep 'RUNPATH|libpq'
 0x0000000000000001 (NEEDED)             Shared library: [libpq.so.5]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/pgsql-12/lib]
```

Removing it solves the problem.

You can check with `ldconfig -p | grep libpq`.

**Comment by rebelate** [comment]
I got a problem building Caffe and turns out it's because of this as well saying 'undefined reference to `PQ' ..
Thanks mate!!

**Comment by jlgranda** [comment]
Hi, I get the same output when compile QField
...
/usr/bin/ld: /usr/lib64/libgdal.so.26: undefined reference to `PQfname@RHPG_9.6'
....

I follow this issue and try erase /usr/pgsql-12/lib/libpq.so.5, but PostgreSQL uninstall. Then I reinstall Postgres server and client.

The problem persist :(

**Comment by jlgranda** [comment]
Finally, I remove all repos for Postgres (e.g PostgreSQL Yum Repository) and install default PostgreSQL in RPMs. This works for me.

**Comment by zhanghao-njmu** [comment]
Thanks! @jlgranda I meet the same problem. 
Finally I found it caused by the **libpq** provided by **pgdg-common** repo. I solved my problem by reinstalling the libpq using the default repo (**AppStream**).
```
sudo yum remove pgdg-redhat-repo.noarch
sudo yum remove libpq
sudo yum install gdal gdal-devel
```

**Comment by jlgranda** [comment]
Yeah!

**Comment by chriskyndrid** [comment]
Commenting on this closed issue as, although these answers are helpful, this issue remains a problem with the PDG postgres libs packages and the default fedora libpq package. This problem can also impact opencv or, presumably, any other library that utilizes libgdal.so and continues to be a problem with Fedora 37.

First you should determine what libgdal.so.XX is pointing to:

```bash
ldd /usr/lib64/libgdal.so.31 | grep libpq
```

If it points at a PDG lib like ``/usr/pgsql-14/lib/libpq.so.5``, then you definitely MAY have an issue. However, the PDG packages also ovewrite the base ``/usr/lib64/libpq.so.5`` libraries on fedora 37, so although removing ``/etc/ld.so.conf.d/postgresql-pgdg-libs.conf`` and rerunning ``ldconfig`` then ``sudo dnf reinstall gdal-libs`` will get libgdal.so.31 to point at the ``/lib64/libpq.so.5`` shared library, this may not fix the problem. 

So after you've done this, you should proceed with 
```bash 
dnf provides /usr/lib64/libpq.so.5
```

if it's not the default Fedora package, and instead points at a PDG package, you'll still have an issue. This is clearly because the gdal-libs package is compiled against the standard libpq packages the distro provides. In my case, it's not acceptable to remove postgres as I use postgres all the time on this machine in my development efforts. Ultimately, in order to band-aide this problem, I did:

```bash
sudo dnf download libpq-14.3-2.fc37.x86_64
rpm2cpio libpq-14.3-2.fc37.x86_64.rpm | cpio -idmv
```

and I manually copied the shared libraries over the /usr/lib64 variant. This will likely be an issue when PDG upgrades packages on my machine(the library package anyway). However, the combination of excluding the inclusion of the ``/etc/ld.so.conf.d/postgresql-pgdg-libs.conf`` file in addition to manually overwriting the PDG /usr/lib64 files resolved the issue in a way that allows you to link against libgdal and not get compile errors(in my case using opencv bindings in rust) while continuing to operating postgres on the local machine.
